# Generated by Django 4.2.1 on 2023-05-12 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_part', '0002_alter_useraccount_person_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='type',
            field=models.CharField(choices=[('shop', 'Магазин'), ('buyer', 'Покупатель')], default='buyer', max_length=5, verbose_name='Тип пользователя'),
        ),
    ]
