# Generated by Django 4.2.1 on 2023-05-19 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_part', '0005_alter_contactuser_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactuser',
            options={'verbose_name': 'Контакты пользователя', 'verbose_name_plural': 'Контакты пользователя'},
        ),
    ]
