# Generated by Django 4.2.1 on 2023-05-24 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_part', '0006_alter_contactuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useraccount',
            options={'verbose_name': 'Пользователи', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
