# Generated by Django 4.2.1 on 2023-05-19 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users_part', '0004_contactuser'),
        ('products', '0014_alter_productinfo_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='contactsuser', to='users_part.contactuser', verbose_name='Пользователь'),
        ),
    ]
